repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=4096]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "-l", "120"]
  - repo: https://github.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        types: [python]
        args: ["--max-line-length", "120", "--ignore", "F811,F841,E203,E402,E712,E501,W503"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        exclude: test
        args: ["--exclude", "SC1091,SC1073,SC2086,SC2128"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: ["-d", "{extends: relaxed, rules: {line-length: {max: 120}}}"]
